# Generated by Django 4.0.6 on 2025-03-21 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_profile_profile_image'),
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudioSettings',
            new_name='Business',
        ),
        migrations.RenameModel(
            old_name='Locations',
            new_name='Location',
        ),
        migrations.RenameModel(
            old_name='Rooms',
            new_name='Room',
        ),
    ]
