# Generated by Codex on 2026-06-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0003_business_time_zone_string"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="noshow_options_prepay",
            field=models.CharField(
                choices=[
                    ("noshow_prepay_nothing", "Do not automatically refund their payment"),
                    ("noshow_prepay_flat", "Automatically refund their payment minus a flat no-show fee"),
                    ("noshow_prepay_percent", "Automatically refund their payment minus a percentage fee"),
                    ("noshow_prepay_fullrefund", "Automatically refund their payment in full without any no-show fee"),
                ],
                default="noshow_prepay_nothing",
                max_length=30,
                verbose_name="When the customer has paid ahead of time and is marked as a no-show during checkin:",
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="noshow_prepay_flatfee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Flat No-Show Fee when Customer Has Prepaid",
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="noshow_prepay_percentfee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Percentage No-Show Fee when Customer Has Prepaid",
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="noshow_options_notprepay",
            field=models.CharField(
                choices=[
                    ("noshow_notprepay_nothing", "Do not charge any no-show fee to their account"),
                    ("noshow_notprepay_flat", "Automatically attempt to charge their payment a flat no-show fee"),
                    ("noshow_notprepay_percent", "Automatically attempt to charge their payment a percentage no-show fee"),
                    ("noshow_notprepay_fullcharge", "Automatically attempt to charge their payment in full as a no-show fee"),
                ],
                default="noshow_notprepay_nothing",
                max_length=30,
                verbose_name="When the customer has not yet paid and is marked as a no-show during checkin:",
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="noshow_notprepay_flatfee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Flat No-Show Fee when Customer Hasn't Prepaid",
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="noshow_notprepay_percentfee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Percentage No-Show Fee when Customer Hasn't Prepaid",
            ),
        ),
    ]
