# Generated by Django 5.2.15 on 2026-06-06 22:35

import administration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_business_noshow_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='time_zone_string',
            field=models.CharField(choices=administration.models.timezone_choices, max_length=32, verbose_name='Time Zone'),
        ),
    ]
