[pytest]
DJANGO_SETTINGS_MODULE = tests.settings
python_files = test_*.py *_tests.py tests.py
testpaths =
    tests
    plugins/booking/tests
    plugins/customforms/tests
    plugins/digitalproducts/tests
    plugins/email_otp/tests
norecursedirs =
    .git
    .github
    .pytest_cache
    media
    static
    plugins/disabled
addopts =
    -ra
