# Generated by Django 4.0.6 on 2025-10-19 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_business_time_zone_string'),
        ('registration', '0004_profile_gcal_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.PositiveIntegerField(default=1, verbose_name='Business ID')),
                ('name', models.CharField(blank=True, max_length=400, null=True, verbose_name='Event Name')),
                ('scheduled_time', models.DateTimeField(verbose_name='Scheduled Date and Start Time')),
                ('duration', models.DurationField(verbose_name='Duration')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.location', verbose_name='Location')),
            ],
        ),
    ]
