# Generated by Django 4.0.6 on 2025-10-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Google Event ID'),
        ),
    ]
